### ISSUE TITLE
Where should this workflow exist?

### ISSUE THREAD

**Issue by ahmedig** [ahmadnassri/action-template-repository-sync#66]
Hello,
Thanks a lot for this awesome action mate, good job!
Just a quick question since your documentation doesn't say where exactly should we put this workflow?
my guess is that it should be in the template itself, so it listens to any update and copies everything through to the dependents.
Is that right? maybe its worth updating the documentation with this piece of information.

Thanks again!

**Comment by ahmadnassri** [comment]
correct, you would put this in the template itself.
